### ISSUE TITLE
Execution error with latestest SF CLI version

### ISSUE THREAD

**Issue by achimraible** [ChuckJonas/sfdx-git-packager#48]
When I call the command "sfdx git:package -s ${sourceBranch} -t ${targetBranch} -d ${tmp.deployment.folder}/diff -f" I get the following error

 [exec]     Error: Package subpath './v4' is not defined by "exports" in 
 [exec]     /node_modules/uuid/package.json
 [exec]     Code: ERR_PACKAGE_PATH_NOT_EXPORTED

I already install this uuid version to the Docker image

RUN npm install uuidv4
NodeJS Version 14.15.1
SF CLI Version 7.81.0 (core)
SFDX Version 50.6.0 (core)

With this versions it works fine
SF CLI Version  7.78.1 (core)
SFDX Version 50.3.1 (core)

**Comment by ChuckJonas** [comment]
I haven't tested yet, but will give it a go when I get a chance.  If you are using this tool in a CI process, I highly recommend that you target a specific version of the sfdx plugin.  

For example, if you are using the Salesforce docker image, you would want to use something like: 
`salesforce/salesforcedx:7.63.0-full` instead of `salesforce/salesforcedx:latest`.

**Comment by ChuckJonas** [comment]
I just tested in a fresh docker container with the latest versions and I don't have any issues... 

```
salesforcedx 50.6.0 (core)
sfdx-cli 7.81.0 (core)
sfdx-git-packager 0.3.2
```

Is the image you are using public?

**Comment by achimraible** [comment]
In order I can't get the plugin up and running again with whatever salesforcdx version I'm using, I created in my deployment script the same functionality you are using. 
Thanks for your help in all the issues I created, but from my point of view it is not further work needed from your side
